FROM apache/airflow:2.11.0

RUN pip install apache-airflow-providers-apache-spark

USER root
RUN apt-get update
RUN apt-get install -y --no-install-recommends openjdk-17-jdk
RUN apt-get clean && rm -rf /var/lib/apt/lists/*

ENV SPARK_HOME="/home/sparkuser/spark"
ENV JAVA_HOME="/usr/lib/jvm/java-17-openjdk-arm64"
ENV PATH="${JAVA_HOME}:${SPARK_HOME}/bin:${SPARK_HOME}/sbin:${PATH}"
ENV SPARK_MASTER_PORT="7077"
ENV SPARK_MASTER_HOST="spark-master"

RUN mkdir -p ${SPARK_HOME}

RUN curl -O https://archive.apache.org/dist/spark/spark-3.5.7/spark-3.5.7-bin-hadoop3.tgz
RUN tar xvzf spark-3.5.7-bin-hadoop3.tgz --directory ${SPARK_HOME} --strip-components 1 \
    && rm -rf spark-3.5.7-bin-hadoop3.tgz

RUN useradd -u 1000 -m -d /home/sparkuser sparkuser
ENV HOME="/home/sparkuser"
RUN chown -R airflow:sparkuser ${SPARK_HOME}

RUN apt update
RUN apt-get -y install procps

COPY ./spark-defaults.conf "${SPARK_HOME}/conf"

USER airflow

# ENTRYPOINT ["/bin/bash"]